- tests/integration/mirrorpeer_controller_test.go
When testing using envtest validation error messages are a
little different from the messages received when testing
against full kubernetes or openshift deployment.
So, this commits removes the error message validation and
retains rest of the error checks.
> remove flaky validation steps

- controllers/manager.go
- controllers/mirrorpeer_controller_test.go
When using a different scheme for testing, we can not catch
issues like missing scheme from manager. So using the same
scheme as manager for reconciler testing.
Also, adding open-cluster-management scheme to manager scheme.
> fix manager scheme & use it for testing reconciler

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/common-controller-utils.go
- controllers/common/secret-utils.go
- controllers/manager.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeersecret_controller.go
- controllers/named-peerref-with-data.go
MirrorPeerSecret watches BLUE secrets in the Hub's
Namespaces and syncs them to the corresponding GREEN
secrets in peered Namespaces.
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>
> Add MirrorPeerSecret controller

- api/v1alpha1/mirrorpeer_types.go
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
- controllers/common/predicate.go
- controllers/mirrorpeer_controller.go
Depends on https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/17
This commit adds the status updates for MirrorPeer resources
```
status:
message: Secret "d8433b8cb5b6d99c4d785ebd6082efd19cad50c" not found
phase: ExchangingSecret
```
Sample status as tested
> MirrorPeer status conditions

- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- bundle/manifests/odfmo-controller-manager_v1_serviceaccount.yaml
- config/manifests/kustomization.yaml
Keep labels of one operator pods always unique from the other
operator pods, So that label based fetching of pods can be more
deterministic.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2005843
> Bug 2005843: Label ODF multicluster operator pod based on deployment name

- addons/token-exchange/manifests/hub_role.yaml
- Agent was not creating BLUE secret for one of the managed cluster.
- Agent logs showed "forbidden User" error.
Added a rule for `Secrets` in hub's `Role`.
> Bug 2006176: token-exchange-agent pod logs flooded with failed to sync and Failed to watch messages

- controllers/mirrorpeer_controller.go
- tests/integration/mirrorpeer_status_test.go
This commit fixes the issue where the status is always ExchangedSecret.
This will check if the secret is not found, then requeue for reconcile
after 5 seconds.
Also add integration tests for Status
Fix for https://github.com/red-hat-storage/odf-multicluster-orchestrator/issues/36
> Fix MirrorPeer status updates

- bundle.Dockerfile
- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- bundle/manifests/odfmo-controller-manager_v1_serviceaccount.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- hack/make/tools.mk
OLM generates the serviceaccount referenced in CSV. So there is no need to manually add serviceaccount manifest to bundle.
This was also fixed in operator sdk v1.13.1 and above (it no longer generates that manifest).
> Fix invalid serviceaccount in bundle

- controllers/mirrorpeer_controller.go
Requeue when the MP status fails to update, and also fixed a typo where
the reconciler is supposed to requeue when the secrets are not found.
> Requeue on status errors

- controllers/common-controller-utils.go
- controllers/common-controller-utils_test.go
- go.mod
- go.sum
Default YAML:
```
kind: RamenConfig
health:
healthProbeBindAddress: :8081
metrics:
bindAddress: 127.0.0.1:9289
webhook:
port: 9443
leaderElection:
leaderElect: true
resourceName: hub.ramendr.openshift.io
ramenControllerType: "dr-hub"
```
After updated by MCO:
```
MaxConcurrentReconciles: 0
apiVersion: ramendr.openshift.io/v1alpha1
health:
healthProbeBindAddress: :8081
kind: RamenConfig
leaderElection:
leaderElect: true
leaseDuration: 0s
renewDeadline: 0s
resourceLock: ""
resourceName: hub.ramendr.openshift.io
resourceNamespace: ""
retryPeriod: 0s
metrics:
bindAddress: 127.0.0.1:9289
ramenControllerType: dr-hub
s3StoreProfiles:
- s3Bucket: odrbucket-9af550a2d48c
s3CompatibleEndpoint: https://s3-openshift-storage.apps.bot-41ec5b55-5728-48b6-8874-936be1c7de01.devcluster.openshift.com …
```
> Fix ramenConfig parse issue using post creating MirrorPeer creation

- go.mod
- go.sum
Before:
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: RamenConfig
health:
healthProbeBindAddress: :8081
metrics:
bindAddress: 127.0.0.1:9289
webhook:
port: 9443
leaderElection:
leaderElect: true
resourceName: hub.ramendr.openshift.io
ramenControllerType: "dr-hub"
drClusterOperator:
deploymentAutomationEnabled: false
channelName: stable-4.10
packageName: odr-cluster-operator
namespaceName: openshift-dr-system
catalogSourceName: redhat-operators
catalogSourceNamespaceName: openshift-marketplace
clusterServiceVersionName: odr-cluster-operator.v0.0.1
```
After ODFMO update
```
apiVersion: ramendr.openshift.io/v1alpha1
drClusterOperator:
catalogSourceName: redhat-operators
catalogSourceNamespaceName: openshift-marketplace
channelName: stable-4.10
clusterServiceVersionName: …
```
> update ramen dependency

- controllers/mirrorpeer_controller.go
- controllers/mirrorpeer_controller_test.go
This commit adds recovery labels for ACM backup and restore.
https://issues.redhat.com/browse/ACM-1001
> Add hub recovery labels to mirrorpeer

- controllers/common-controller-utils.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeersecret_controller.go
- controllers/named-peerref-with-data.go
Fixes: https://github.com/red-hat-storage/odf-multicluster-orchestrator/issues/76
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
> Ignore logging credentials

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/agent_mirrorpeer_controller_test.go
- addons/token-exchange/manifests/spoke_deployment.yaml
- addons/token-exchange/rook_secret_handler.go
- addons/token-exchange/s3_secret_handler.go
- addons/token-exchange/secret_exchange_handler_register.go
- addons/token-exchange/token_exchanger_addon.go
- addons/token-exchange/token_exchanger_agent.go
- api/v1alpha1/mirrorpeer_types.go
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
- controllers/mirrorpeer_controller.go
- controllers/utils/s3.go
- tests/integration/managedclusteraddon_test.go
- tests/integration/mirrorpeer_controller_test.go
- tests/integration/mirrorpeer_status_test.go
- tests/integration/mirrorpeersecret_controller_test.go
This commit adds support for Metro DR (sync mode)
The following changes are added -
1. Add DRType to MirrorPeer (sync/asyn)
2. Add annotation to ManagedClusterAddon for custom handlers
3. Changes to test to include DRType for MirrorPeer
4. Changes to spoke deployment and addition of handlers flag
5. Sync = S3ProfileSync only, Async = Just like before 
https://issues.redhat.com/browse/RHSTOR-2542
> Support for Metro DR (Sync Mode) 

- addons/token-exchange/manifests/spoke_clusterrole.yaml
- addons/token-exchange/manifests/spoke_clusterrolebinding.yaml
- addons/token-exchange/token_exchanger_addon.go
This commit adds permission to spokeclusterrole and bindings to give
MirrorPeer watch permissions to the default agent user
> No more watch errors (Hopefully!)

- addons/token-exchange/secret_exchange_handler_register.go
- controllers/mirrorpeer_controller.go
- tests/integration/managedclusteraddon_test.go
This commit fixes a bug where the annotations are not correctly passed
to managedclusteraddon and it does not fail if it is invalid.
It also updates the integration tests to check the presence and validity of the
annotations
> Fix sync mode and fail if it is invalid

- api/v1alpha1/mirrorpeer_webhook.go
No point in allowing changing the type of the MirrorPeer if the clustersets are
immutable
> Make type to be immutable

- .github/workflows/lint.yaml
- .github/workflows/publish-images.yaml
- .github/workflows/test-and-build.yaml
- Update some actions from v2 to v3
- Enable testing with Go 1.16 and 1.17
- Update golangci-lint version to 1.45.2
- Update kube-lint version to 1.4.2
> update CI workflows and dependencies

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/agent_mirrorpeer_controller_test.go
- addons/token-exchange/manifests/spoke_clusterrole.yaml
- controllers/utils/hash.go
This commit does the following things
1. Agent MirrorPeer controller labels the RBD StorageClasses with these
FSID for each managedcluster
2. Agent MirrorPeer controller labels the VRC with replicationids
generated through FSIDs of each managed cluster
> Label VRCs and RBD StorageClasses with Ramen Labels

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/agent_mirrorpeer_controller_test.go
- addons/token-exchange/manifests/spoke_clusterrole.yaml
- addons/token-exchange/rook_secret_handler.go
- api/v1alpha1/mirrorpeer_types.go
- controllers/common_controller_utils.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeer_controller_test.go
- controllers/utils/peer_ref.go
- controllers/utils/secret.go
- controllers/utils/slice.go
- go.mod
- go.sum
- tests/integration/mirrorpeersecret_controller_test.go
This PR adds the deletion workflow to the MCO, The manager pod and the token exchange pod add a finalizer to the mirrorpeer to allow for things to get deleted. 
- ManagedClusterAddon gets added with owner refs to the MirrorPeer
- The manager controller first waits for the agent to remove its finalizer, then goes ahead and delete's the PeerRef's Secret if it's not being used any other MirrorPeer.
- The agent also checks if the PeerRef is being used by another MirrorPeer, if it's not then it disables mirroring and CSI addons volume replication
- Delete the volume replication classes based the scheduling intervals and if it's being used or not
- Deletes the green s3 secrets in the storage cluster namespace
- Deletes s3 buckets based on the combination of peerRefs in the MirrorPeer
> Delete resources while deleting MirrorPeer

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/mirrorpeer_controller.go
This commit will add watch permissions for deployment, services,
consoleplugin and DRCluster resources to the manager controller
> Add watch permissions to mirrorpeer controller

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/mirrorpeer_controller.go
- controllers/utils/slice.go
This commit adds changes that binds the hub's clusterrole to generated
spoke users.
This is done to fix a bug where the tokenagent on the spokeclusters are
unable to watch and make channges to mirrorpeer on the hub
> Adds bindings for spoke users on hub

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/mirrorpeer_controller.go
This commit adds changes that binds the hub's clusterrole to generated
spoke users.
This is done to fix a bug where the tokenagent on the spokeclusters are
unable to watch and make channges to mirrorpeer on the hub
> Bug 2087145: [release-4.10] Add bindings for spoke users on hub

- addons/token-exchange/agent_mirrorpeer_controller.go
- api/v1alpha1/mirrorpeer_types.go
- controllers/mirrorpeer_controller.go
This commit fixes a bug where the DRCluster objects are not created
properly for MetroDR due to absence of secrets for external mode.
As a temporary workaround, the region for the DRCluster will be empty in case of sync mode and needs to be updated by user.
This workaround needs to be there till external mode clusters are
supported throughout MCO.
The MirrorPeer phase has two new phases for sync mode, S3ProfileSynced
and S3ProfileSyncing.
> Sync mode fixes and status updates

- hack/make/tools.mk
The GOFLAGS is set to -mod=vendor when running on Openshift CI
Unsetting this flag is necessary for go install to work properly.
> Set goflags to empty when using go install

- addons/token-exchange/rook_secret_handler.go
The current filter when fetched from env is empty and matches for every secret created. To avoid this, we set the filter to a default string.
`I0912 07:34:38.614299       1 blue_secret_controller.go:76] reconciling addon deploy "openshift-storage/rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-keyring"
E0912 07:34:38.614438       1 base_controller.go:270] "managedcluster-secret-tokenexchange-controller" controller failed to sync "openshift-storage/rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-keyring", err: failed to get the storage cluster name from the secret "rook-ceph-mds-ocs-storagecluster-cephfilesystem-b-keyring" in namespace "openshift-storage" in managed cluster. Error could not get storageCluster name`
> Set default filter string

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/blue_secret_controller.go
- addons/token-exchange/blue_secret_controller_test.go
- addons/token-exchange/rook_secret_handler.go
- addons/token-exchange/rook_secret_handler_test.go
- addons/token-exchange/s3_secret_handler.go
- addons/token-exchange/secret_exchange_handler_interface.go
- controllers/mirrorpeer_controller.go
- controllers/utils/cluster.go
- controllers/utils/secret.go
- controllers/utils/secret_test.go
This commit fixes the following issues -
1. Fixes issue with detecting multiple secrets and syncing wrong secrets
2. Fixes issue with properly detecting whether a cluster is in external mode or converged mode.
3. Small fixes related to unmarshalling of external rook secret
4. Add unit tests for unmarshallling
5. Fixes issue with DRCluster not using the correct fsid key to get from secret.
6. Fixes tests to accommodate the above fixes
7. Fixes labelling of storageclasses with fsid, requeues the requests after 60 seconds to avoid barrage of errors in the logs
Tested for Async mode.
MirrorPeer is in exchanged phase after 5-7 mins 
> Fix issues with secret exchange

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/agent_mirrorpeer_controller_test.go
- addons/token-exchange/rook_secret_handler.go
- addons/token-exchange/token_exchanger_agent.go
- controllers/mirrorpeer_controller.go
The commit does the following changes -
- From 4.12 onwards, Volume replication CSI addon is enabled by default on all odf
clusters. We do not need to enable on and off through the operator.
- Adding additional logs and cleaning the error logs when the secrets
are not found. Instead just doing an info log and requeing the key
till the secrets are available
- Shuffling few of the operations in agent controller for creating s3
buckets and delaying operations that require secret exchange.
- SharedInformer will resync duration of 2 mins instead of 10 min. This
will allow fast detection of secrets and the help with hastening the
operations
> Bug 2126008: Fix token-exchange and functionality enhancements

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/rook_secret_handler.go
- addons/token-exchange/rook_secret_handler_test.go
- addons/token-exchange/secret_exchange_handler_utils.go
- controllers/common_controller_utils.go
- controllers/utils/s3.go
Removed secret type check for rook-ceph-mon and cluster-peer-token
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
> Fix tokenexchange flow for external cluster

- addons/token-exchange/manifests/spoke_deployment.yaml
This is to ensure that the tokenexchange controllers are completely started and the servers are running before starting the probe checks
> Bug 2130704: Add delay to liveness and readiness probes

- Makefile
We were updating SkipRange annotation after the bundle was generated. So, CSV does not have SkipRange annotation which then blocks upgrades.
This issue is difficult to catch as it only happens on the first run of bundle generation. Subsequent bundle generation gets the annotation correctly.
> fix skipRange update to CSV

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/manifests/bases/odf-multicluster-orchestrator.clusterserviceversion.yaml
These labels are used by operator-framework to determine archs supported by the operator.
> add labels for supported arch

- addons/token-exchange/token_exchanger_agent.go
This commit fixes an with addon leader election. The leader election gets stuck on acquiring lock for the namespace lease. This fix disables the leader election process for addons as it is not required for a single replica deployments.
Main branch PR: https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/152
> Bug 2183198: [release-4.12] Disables leader election for addons

- addons/token-exchange/agent_mirrorpeer_controller.go
- api/v1alpha1/mirrorpeer_types.go
- api/v1alpha1/mirrorpeer_webhook.go
- config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
- go.mod
- go.sum
When requested, enable multiclusterservice on StorageCluster in all the ManagedClusters referenced by MirrorPeer.
```
spec:
...
overlappingCIDR: true
```
> enable multiclusterservice on storagecluster

- addons/maintainence-agent/maintenance_mode_controller.go
- addons/maintainence-agent/manager.go
- addons/setup/maintenance-manifests/spoke_clusterrole.yaml
- addons/setup/maintenance-manifests/spoke_role.yaml
- addons/setup/tokenexchange-manifests/spoke_clusterrole.yaml
- addons/setup/tokenexchange-manifests/spoke_role.yaml
- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/manager.go
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- controllers/manager.go
- controllers/utils/cluster.go
This commit fixes the following issues -
1. Conflict error issues with the finalizer
2. Checks if StorageCluster mirroring is enabled before scaling.
3. Status update done at the end of reconciliation
4. Returns only a single cephcluster instead of an array as the targetId should only return single unique cephcluster
> Fixes for MMode reconciler

- controllers/mirrorpeersecret_controller.go
This commit fixes issue where s3 profile config is not updated in the Ramen config map. This is due to a race condition existing between MCO and Ramen where Ramen starts after MCO during upgrade at which point s3profile is updated and  Ramen replaces this with newly created default config.
This fix will ensure that any changes to Ramen configmap is watched and triggers reconcile for all secrets in the current namespace which should ensure that s3profile is properly updated regardless of the upgrade sequence.
> Fix issue with empty s3 profile config

- controllers/drpolicy_controller.go
This commit adds changes to requeue the request after 10 secs if the mirrorpeer is not found on the hub. For avoiding errors due to racing with creation of MirrorPeer.
> Requeue DRPolicy if no mirrorpeers found

- config/manager/manager.yaml
- controllers/drpolicy_controller.go
- controllers/drpolicy_controller_test.go
This commit fixes the issue with hub recovery where the new hub cluster does not have managedcluster CRs updated due to clusterclaims on the managed clusters being in an non updated state.
We are changing the method from looking into the MC CRs to fetching it from the rook secret synced on hub.
> Fetches cluster fsid through secret and not mc

- addons/token-exchange/rook_secret_handler_test.go
- addons/token-exchange/s3_secret_handler_test.go
- addons/token-exchange/secret_exchange_handler_utils.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeer_controller_test.go
- controllers/mirrorpeersecret_controller.go
- controllers/utils/secret.go
These commits add label changes to the generated source secret as well as the ones present on the hub to make them a candidate for ACM backup and restore (https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/backup_and_restore)
This is done as a fix to hub recovery issue where secrets are not generated due when both the active hub and primary cluster being co-situated on the same site or zone. This causes the VRC to not be created on the remaining managed clusters and failover fails.
> Bug 2267885: Add hub recovery labels for backing up secrets

- addons/blue_secret_controller.go
- addons/secret_exchange_handler_utils.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeer_controller_test.go
- controllers/mirrorpeersecret_controller.go
- controllers/utils/secret.go
These commits add label changes to the generated source secret as well as the ones present on the hub to make them a candidate for ACM backup and restore (https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html-single/backup_and_restore)
This is done as a fix to hub recovery issue where secrets are not generated due when both the active hub and primary cluster being co-situated on the same site or zone. This causes the VRC to not be created on the remaining managed clusters and failover fails.
> Add hub recovery labels for backing up secrets

- controllers/drpolicy_controller.go
The commit fixes a bug where it throws a nil pointer reference when no error or mirrorpeer is returned from the function
> Return not found error

- controllers/common_controller_utils.go
- go.mod
- go.sum
Ramen S3Profiles spec has two more fields which are related to velero/OADP and they are not managed by MCO. However, MCO is currently overwriting them when s3 profile updates. This PR addresses that.
> Check and update only those fields that MCO is interested in S3Profiles

- controllers/drpolicy_controller.go
- controllers/drpolicy_controller_test.go
If DRPolicy is created with flattening enabled, we create 2 VRC - 1 without flattening and 1 with flattening. VRC without flattening is marked as default VRC and VRC with flattening is given a unique label.
> create VRC with flattenMode=force

- addons/agent_mirrorpeer_controller.go
- addons/manager.go
- api/v1alpha1/mirrorpeer_types.go
- api/v1alpha1/mirrorpeer_webhook.go
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
- go.mod
- go.sum
MirrorPeer.Spec.OverlappingCIDR was added to allow users to automatically enable StorageCluster.Spec.Netowrking.MultiClusterService when needed. But this implementation had some limitations due to which it was not generally used.
This commit now drops the changes completely to avoid unwanted usage. This will be replaced by alternate solutions which are more reliable.
> remove unused configuration of MultiClusterService

- .github/workflows/publish-images.yaml
- .github/workflows/test-and-build.yaml
- Makefile
- hack/make/vars.mk
This change provides the flexibility to use different container build tools by simply setting the `BUILD_TOOL` variable.
> Refactor Makefile to support customizable build tool

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/managedcluster_controller.go
- controllers/managedcluster_controller_test.go
- controllers/managedclusterview_controller.go
- controllers/managedclusterview_controller_test.go
- controllers/manager.go
- controllers/mirrorpeer_controller.go
- controllers/utils/managedcluster.go
- controllers/utils/managedclusterview.go
- controllers/utils/managedclusterview_test.go
- go.mod
- go.sum
- Added reconciliation logic for `ManagedCluster`
- Added tests for `ManagedClusterReconciler` reconciliation logic and ensure ManagedClusterViews function.
- Reconciliation for ManagedCluster creates ManagedClusterView which pulls the ‘odf-info’ configmap onto the hub.
- Updated RBAC rules in `config/rbac/role.yaml` to include permissions for ManagedClusterView resources. (ManagedCluster RBAC already there)
- Plumbing to make the controllers work like the items above
- Updated go.mod and go.sum to include `github.com/stolostron/multicloud-operators-foundation`.
> Implement reconciliation for ManagedCluster and create ManagedClusterView

- console/console.go
- console/console_test.go
- controllers/manager.go
Ref: https://github.com/red-hat-storage/odf-operator/pull/441
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2302257
> console: use github.com/openshift/api/console/v1

- controllers/managedclusterview_controller.go
- controllers/managedclusterview_controller_test.go
- Updated the `createOrUpdateConfigMap` function to handle nested data structures correctly, ensuring that YAML content is properly extracted and parsed.
- Adjusted the logic to filter for YAML keys in the ManagedClusterView data and marshal the parsed data into JSON for storage in the ConfigMap.
- Ensured that the `Controller` field in the OwnerReferences is set to `false` where necessary to prevent conflicts.
- Modified unit tests to reflect the changes in the data structure and logic, ensuring accurate validation of the ConfigMap content and OwnerReferences.
- Fixed a bug where the `Scope` check in the `hasODFInfoInScope` function was incorrectly using `Kind` instead of `Resource`.
> Bug 2308144: Correct ConfigMap creation logic and update unit tests

- controllers/mirrorpeer_controller.go
- go.mod
- go.sum
The commit also make changes to implementation of StorageClusterPeer creation due to the api update
> Update deps for OCS and changes to StorageClusterPeer creation

- controllers/managedclusterview_controller.go
- controllers/managedclusterview_controller_test.go
- controllers/mirrorpeer_controller.go
- controllers/utils/configmap.go
- controllers/utils/manifestwork.go
- go.mod
- go.sum
- Added `ClientID` to `ClientInfo` struct for unique client identification.
- Updated `Reconcile` to invoke `createManifestWorkForClusterPairingConfigMap`.
- Implemented `createManifestWorkForClusterPairingConfigMap` to manage client pairings via ConfigMap in ManifestWork.
- Ensured each client is paired with exactly one other client in the ConfigMap.
- Added helper functions `DecodeConfigMap` and `GetManifestWork` in utils.
- Updated dependencies in `go.mod` and `go.sum`.
> Manage client pairings via createManifestWorkForClusterPairingConfigMap

- addons/agent_mirrorpeer_controller.go
- addons/agent_mirrorpeer_controller_test.go
- addons/rook_secret_handler.go
OCS operator API dependency has been changed recently,
MirroringSpec is changed to pointer: [https://github.com/red-hat-storage/ocs-operator/commit/24092a02c1c1288ac8f96bf89aeb17280fa49d3a#diff-56afead82aaf51a0042[…]ed85210d2b6eed847d3f87R89](https://github.com/red-hat-storage/ocs-operator/commit/24092a02c1c1288ac8f96bf89aeb17280fa49d3a#diff-56afead82aaf51a00424b12238a93c094ce469f981ed85210d2b6eed847d3f87R89)
So the recent, OCS API dependency on MCO is started breaking with nil pointer exception: [https://github.com/red-hat-storage/odf-multicluster-orchestrator/commit/5899bfa27128c0120f5c083a97977d60c0288404#diff-3295df72345[…]8042d9f42d63R734](https://github.com/red-hat-storage/odf-multicluster-orchestrator/commit/5899bfa27128c0120f5c083a97977d60c0288404#diff-3295df7234525439d778f1b282d14 …
> Initialize Mirroring spec to avoid nil pointer exception

- controllers/utils/hash.go
There are two separate methods to generate hashes based on whether RDR is done for provider mode or internal mode
The one for internal mode is being reverted in this commit as the it was causing issues with upgrades
https://issues.redhat.com/browse/DFBUGS-961
> Fix issue with the hash generation for MirrorPeer

- addons/agent_mirrorpeer_controller.go
- controllers/mirrorpeer_controller.go
Restricting to the fetching of cephFSID for when the MirrorPeer is not for StorageClients
Requeue if MirrorPeer is in Phase: ExchangingSecret
> addons: move the fetching of cephfsid only for non-provider mode

- controllers/utils/hash.go
- controllers/utils/s3.go
To fix a bug where the length of the generated bucket name is larger than what is required
> Fix the length of generated OBC bucket name

- addons/agent_mirrorpeer_controller.go
- addons/agent_mirrorpeer_controller_test.go
- addons/blue_secret_controller_test.go
- addons/green_secret_controller_test.go
- addons/rook_secret_handler.go
- addons/setup/tokenexchange-manifests/spoke_clusterrole.yaml
- controllers/drpolicy_controller.go
- controllers/drpolicy_controller_test.go
- controllers/named_peerref_with_data.go
- controllers/utils/hash.go
- controllers/utils/hash_test.go
- controllers/utils/secret.go
- tests/integration/mirrorpeer_status_test.go
- tests/integration/mirrorpeersecret_controller_test.go
- tests/integration/ramen_test.go
Adds a new StorageID field to blue/green secrets and updates the replication ID generation to use storage IDs instead of FSIDs. Key changes:
- Add storage_id field to all secret types (blue/green/hub)
- Update secret handlers to properly propagate storage IDs between secrets
- Add helper functions to get storage IDs from different secret types
- Update replication ID generation to use storage IDs instead of FSIDs
- Add tests for storage ID handling and verification
- Update labelCephClusters to use storage IDs for replication ID
> feat: Add StorageID field to secrets and use it for replication ID

- addons/agent_mirrorpeer_controller.go
- addons/agent_mirrorpeer_controller_test.go
- addons/s3_secret_handler.go
- controllers/utils/hash.go
- controllers/utils/peer_ref.go
- controllers/utils/peer_ref_test.go
- controllers/utils/s3.go
- controllers/utils/s3_test.go
Using different naming scheme for internal and provider mode could cause issues later on if/when users want to move between modes. So, this commit reverts the special handling for provider mode during OBC name generation, S3 profile name generation and S3 secret name generation for the hub.
This does not address changes required for certain usecases like multiple clients on same cluster.
> use same S3 naming scheme for internal and provider mode

- Makefile
- addons/agent_mirrorpeer_controller.go
- addons/manager.go
- addons/s3_controller.go
- cmd/root.go
- controllers/common_controller_utils.go
- controllers/common_controller_utils_test.go
- controllers/drpolicy_controller.go
- controllers/drpolicy_controller_test.go
- controllers/managedcluster_controller.go
- controllers/managedclusterview_controller.go
- controllers/managedclusterview_controller_test.go
- controllers/manager.go
- controllers/mirrorpeer_controller.go
- controllers/mirrorpeer_controller_test.go
- controllers/mirrorpeersecret_controller.go
- controllers/utils/clients.go
- controllers/utils/env.go
- controllers/utils/peer_ref.go
- controllers/utils/s3.go
- controllers/validations.go
- go.mod
- go.sum
The changes in this PR started off as a way to enable development and testing on local environment.  But, the changes are useful beyond that.
- [run golangci-lint before integration tests](https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/279/commits/869db06f8171dbffe2dbf5f8a6855bb864f82c37)
Before running integration tests, we want to catch linter error just like we do with unit tests.
- [explicitly name the MirrorPeer controller on spoke](https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/279/commits/b7f636461bc2273da0040ed4d045f027275eb037)
We have 2 MirrorPeer controllers - one runs on the hub and the other
runs on spoke cluster. If in case, same cluster is used as hub and spoke,
there are chances of one of these controllers failing to register …
> Batch update codebase

- controllers/drpolicy_controller.go
- controllers/utils/predicate.go
WatchObjectMeta does not watch for changes in content of secrets. We need to use Watch on Secrets. To filter the list of secrets, we add a predicate to only watch for source secrets.
Also, added  some debug logs to help us track reconcile requests during debugging.
> add secret watcher and debug logs to DRPolicy reconciler

- controllers/drpolicy_controller.go
- controllers/utils/predicate.go
DRPolicy reconciler no longer depends on contents of the source secret. So, we no longer need to watch for it.
Depends on #285
> remove watch on source secret from DRPolicy reconciler

- controllers/drpolicy_controller.go
- controllers/drpolicy_controller_test.go
This PR implements a feature to create an OpenShift Template object which contains a VRC object.
We do not directly create the VRC object. There will be a follow-up PR which will enable the distribution of VRC from provider to clients.
> Create a template for VRC creation on provider cluster

- controllers/mirrorpeer_controller.go
- tests/integration/mirrorpeer_controller_test.go
- tests/integration/ramen_test.go
DRCluster resource requires S3ProfileName. We can only get it if we are the ones managing S3 configuration. So, we check if we are managing S3, get the S3 profile name and create DRCluster.
> fix DRCluster creation

- controllers/utils/s3.go
When creating or updating an OBC, we only manage certain fields. There are other fields managed by other agents. We should not reset those fields whhen we update the resource.
> DFBUGS-2276: ensure OBC spec is not reset unexpectedly

- controllers/utils/hash_test.go
- controllers/utils/storageclass.go
There can be cases where Ceph FSID is not yet initialized or missing from the server response. In such cases, it is better to error out early than to proceed with incorrect state.
> handle corner cases for StorageID generation

- controllers/mirrorpeer_controller.go
- controllers/utils/manifestwork.go
- controllers/validations.go
This is to ensure we wait for StorageClusterPeer to reach Peered state before finishing the reconcile.
> add StorageClusterPeer status feedback to ManifestWork

- addons/agent_mirrorpeer_controller.go
- addons/agent_mirrorpeer_controller_test.go
- addons/manager.go
- addons/setup/addon_setup.go
- addons/setup/tokenexchange-manifests/spoke_deployment.yaml
- controllers/mirrorpeer_controller.go
- controllers/utils/peer_ref.go
- controllers/utils/s3.go
Currently, getPeerRefType function checks for clienttype differently for a managedcluster vs hub cluster. In case, of managed cluster it checks the odf-info cm present in the managecluster and in such a case if we have clients with different storageclusterref then it will return wrong clientType.
Instead, use "odf-client-info" cm present on hub to check for storageclienttype of the managedclusters part of a mirrorpeer such that if we have storageclients with different storageclusterref we are able to verify the type correctly.
> use odf-client-info cm to check peerRefType
