- LICENSE
> add Apache License 2.0

- README.md
> add initial readme

- .github/.kube-lint-config.yaml
- .github/workflows/docker-build.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/integration-test.yaml
- .github/workflows/kube-lint.yaml
* docker build
* integration tests
* golangci-lint
* kube-lint
> add github actions

- Makefile
- tests/integration/mirrorpeer_controller_test.go
- tests/integration/suite_test.go
Tests to ensure that server side validations are working on MirrorPeer CR.
> add tests to ensure validations on MirrorPeer CR

- Makefile
- hack/make/tools.mk
- hack/make/vars.mk
> Makefile cleanup and changes to build & push images

- bundle.Dockerfile
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- bundle/manifests/odfmo-controller-manager_v1_serviceaccount.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/rbac/kustomization.yaml
This commit updates the kustomize configurations to disable
unused params and generates a default operator bundle. It also
generates a bundle.Dockerfile which can be used to build a bundle
image for this operator.
> update kustomize configs and generate bundle

- Makefile
> run integration test in vendor mod in OpenShift CI

- .github/workflows/publish-images.yaml
> add gh action to publish images on push to master

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/manager/manager.yaml
Increased resources.limits.memory from 30Mi to 300Mi.
Increased resources.requests.memory from 20Mi to 200Mi.
> increase memory resource for the operator

- addons/token-exchange/green_secret_controller.go
- addons/token-exchange/green_secret_controller_test.go
- addons/token-exchange/token_exchanger_agent.go
- go.mod
Watches for green secrets on the hub and syncs them to the managed cluster. 
TODO:
Signed-off-by: Santosh Pillai <sapillai@redhat.com>
> sync green secrets from hub to managed clusters

- addons/token-exchange/green_secret_controller.go
- addons/token-exchange/green_secret_controller_test.go
Signed-off-by: Santosh Pillai <sapillai@redhat.com>
> fix data stored in the secret copied from hub to managed cluster

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/s3_secret_handler.go
- controllers/common/s3-utils.go
Added error handling for GetCurrentStorageClusterRef method that would
otherwise cause a nil pointer dereference.
Fixes: #61
> Add error handling for GetCurrentStorageClusterRef

- addons/token-exchange/s3_secret_handler.go
After Fix:
```
- s3profilename: s3profile-remote-cluster-ocs-storagecluster
s3bucket: odrbucket-9af550a2d48c
s3compatibleendpoint: https://s3-openshift-storage.apps.odf-dade9868-20fb-471e-bcd0-3fefc21db2bf.devcluster.openshift.com
s3region: nooba
s3secretref:
name: 2152428ad05a47e326a4b6ae6adfcaa21f2896c
namespace: openshift-dr-system
```
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
> Set default S3Region when not provided

- OWNERS
> Add vbnrh to OWNERS

- Makefile
- bundle/metadata/annotations.yaml
- bundle/metadata/dependencies.yaml
- config/dependencies/dependencies.yaml
- hack/make/vars.mk
Updated the ramen dependencies and added the DRPolicy
> updated ramen dependencies

- hack/make/tools.mk
> Update operator-sdk version in tools to 1.17

- addons/token-exchange/agent_mirrorpeer_controller.go
- addons/token-exchange/agent_mirrorpeer_controller_test.go
- controllers/common_controller_utils.go
- controllers/mirrorpeer_controller.go
- controllers/utils/secret.go
- controllers/utils/secret_test.go
- tests/integration/mirrorpeer_status_test.go
This commit refactors a few common activities like fetching secret, unmarshing
rook secret and s3 secret for usage for consistency across the project.
> Refactors for some common activities

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/console/console_init.yaml
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
> Bug 2079866: Remove invalid arg from odf-multicluster-console deployment

- controllers/common_controller_utils.go
- controllers/common_controller_utils_test.go
> Remove namespace from s3profile secret ref

- addons/token-exchange/agent_mirrorpeer_controller.go
- controllers/mirrorpeer_controller.go
> Limit the length of finalizer if more than 63 char

- Makefile
- bundle/manifests/multicluster.odf.openshift.io_mirrorpeers.yaml
- config/crd/bases/multicluster.odf.openshift.io_mirrorpeers.yaml
- config/rbac/role.yaml
- config/webhook/manifests.yaml
- hack/make/tools.mk
> Update controller-gen to v0.9.2

- addons/token-exchange/secret_exchange_handler_register.go
> Bug 2135246: Fix controller startup issues with metro-dr

- addons/token-exchange/manifests/spoke_deployment.yaml
- addons/token-exchange/token_exchanger_agent.go
> Bug 2130704: Add health probes to tokenexchange agent

- Makefile
- bundle.Dockerfile
- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/manifests/bases/odf-multicluster-orchestrator.clusterserviceversion.yaml
This commit adds disconnected environment annotation to CSV and adds images required by CSV to relatedImages spec.
> add disconnected environment support to operator

- Makefile
> fix kustomize patches for skiprange and replaces

- controllers/mirrorpeersecret_controller.go
This commit fixes issue where s3 profile config is not updated in the Ramen config map. This is due to a race condition existing between MCO and Ramen where Ramen starts after MCO during upgrade at which point s3profile is updated and  Ramen replaces this with newly created default config.
This fix will ensure that any changes to Ramen configmap is watched and triggers reconcile for all secrets in the current namespace which should ensure that s3profile is properly updated regardless of the upgrade sequence.
> Bug 2217549: Fix issue with empty s3 profile config

- go.mod
- go.sum
Ramen API has added new fields to support discovered apps. The fields are in ramenConfig and DRPC.
> go: upgrade ramen api to latest

- controllers/mirrorpeer_controller.go
This commit fixes issue with mutate fn for controllerutil createOrUpdate function
> Bug 2279890: Fix createOrUpdate for rolebindings

- go.mod
- go.sum
updating vault version will help in avoiding CVEs issue.
> cve: update vault version

- addons/blue_secret_controller_test.go
- addons/green_secret_controller_test.go
- addons/s3_controller_test.go
- Add unit tests for blue controller
- Add unit tests for green controller
- Add unit tests for s3 controller
> Add unit tests for secret controllers

- go.mod
- go.sum
cve: update vault version
Backport of #209
> Bug 2299671: [release-4.16] update vault version

- console/console.go
- console/console_test.go
- controllers/manager.go
Manual cherry-pick of https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/229
The target release is 4.16.3
> Bug 2302463: console: use github.com/openshift/api/console/v1

- bundle/manifests/odf-multicluster-orchestrator.clusterserviceversion.yaml
- config/console/console_init.yaml
Fix https://issues.redhat.com/browse/DFBUGS-258
> Remove auto-mount for default ServiceAccount token

- addons/agent_mirrorpeer_controller.go
This is a stop-gap solution while we work on a better fix. Commented out code is intentional to preserve original intent.
> remove cleanup of StorageClusterPeer token

- addons/agent_mirrorpeer_controller.go
- addons/agent_mirrorpeer_controller_test.go
CSI addons spec will be managed internally by ODF. Also, mirroring configuration is now based on StorageClusterPeer CR instead of StorageCluster.Spec.Mirroring.
> unmanage CSI addons and StorageCluster.Spec.Mirroring configuration

- addons/agent_mirrorpeer_controller.go
> fix secret watcher for agent MirrorPeer reconciler

- controllers/mirrorpeer_controller.go
Since MirrorPeerReconciler depends on the data from odf-client-info ConfigMap, we watch for it. As there is no easy way of determining what changed in the data, we reconcile all MirrorPeer objects.
> add watch on odf-client-info ConfigMap for MirrorPeer reconciler

- controllers/mirrorpeer_controller.go
ManagedClusterAddon that is created by the MirrorPeer controller should have a controller reference of the MirrorPeer on it and it should be watched by the controler.
When a ManagedClusterAddon already exists, subsequent updates to it should update metadata and specs as needed.
> add a watch for ManagedClusterAddon and apply correct updates

- addons/agent_mirrorpeer_controller.go
This is a manual cherry-pick of #286
> DFBUGS-1847: [release-4.18] fix secret watcher for agent MirrorPeer reconciler

- addons/agent_mirrorpeer_controller_test.go
- addons/blue_secret_controller_test.go
- controllers/utils/cluster.go
- controllers/utils/storageclass.go
This is a manual backport of #300
> DFBUGS-1847: [release-4.18] fix StorageID generation as per new scheme

- controllers/validations.go
add a check to verify if the ManifestWork.Status.ResourceStatus has been updated with the manifest lists before accesssing them.
Ref:
```
{"level":"error","ts":1752674604.9986584,"caller":"controllers/validations.go:146","msg":"Observed a panic","controller":"mirrorpeer","controllerGroup":"multicluster.odf.openshift.io","controllerKind":"MirrorPeer","MirrorPeer":{"name":"mirrorpeer-sample"},"namespace":"","name":"mirrorpeer-sample","reconcileID":"4f64fc85-3103-4f4d-83e7-b4d45bf19237","panic":"runtime error: index out of range [0] with length 0","panicGoValue":"runtime.boundsError{x:0, y:0, signed:true, code:0x0}","stacktrace":"goroutine 661 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x31d6f90, 0xc00511ed20}, {0x2aee660, …
```
> fix panic when accessing empty ResourceStatus in ManifestWork

- OWNERS
> add nikhil-ladha to owners
